// <auto-generated />
using System;
using BMI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BMI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201109084323_add_table_destroy")]
    partial class add_table_destroy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BMI.Models.DestroyModel", b =>
                {
                    b.Property<int>("id_destroy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bmi_code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pt")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_destroy");

                    b.HasIndex("bmi_code");

                    b.HasIndex("pt");

                    b.ToTable("destroy");
                });

            modelBuilder.Entity("BMI.Models.Fgmodel", b =>
                {
                    b.Property<int>("id_fg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("plant")
                        .HasColumnType("int");

                    b.Property<float>("price_lbs")
                        .HasColumnType("real");

                    b.Property<float>("processing_fee")
                        .HasColumnType("real");

                    b.Property<string>("sap_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("std_price")
                        .HasColumnType("real");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id_fg");

                    b.HasIndex("sap_code");

                    b.ToTable("Fg");
                });

            modelBuilder.Entity("BMI.Models.MasterBMIModel", b =>
                {
                    b.Property<string>("bmi_code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("daily_category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("index")
                        .HasColumnType("real");

                    b.Property<string>("index_category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("index_cs")
                        .HasColumnType("real");

                    b.Property<float?>("index_lb")
                        .HasColumnType("real");

                    b.Property<float>("lbs")
                        .HasColumnType("real");

                    b.Property<string>("sap_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("weekly_category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("zafc_cs")
                        .HasColumnType("real");

                    b.Property<float?>("zafc_kg")
                        .HasColumnType("real");

                    b.HasKey("bmi_code");

                    b.ToTable("Master_BMI");
                });

            modelBuilder.Entity("BMI.Models.Masterdatamodel", b =>
                {
                    b.Property<string>("sap_code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("lbs")
                        .HasColumnType("real");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("sap_code");

                    b.ToTable("Master_data");
                });

            modelBuilder.Entity("BMI.Models.PTModel", b =>
                {
                    b.Property<string>("id_pt")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("batch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("plant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("po")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pt")
                        .HasColumnType("int");

                    b.HasKey("id_pt");

                    b.ToTable("pt");
                });

            modelBuilder.Entity("BMI.Models.ProductionInputModel", b =>
                {
                    b.Property<int>("id_productioninput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bmi_code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("id_pt")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("landing_site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("po")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<string>("raw_source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id_productioninput");

                    b.HasIndex("bmi_code");

                    b.HasIndex("id_pt");

                    b.ToTable("Production_input");
                });

            modelBuilder.Entity("BMI.Models.ProductionOutputModel", b =>
                {
                    b.Property<int>("id_productionoutput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bmi_code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("id_pt")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("po")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<string>("saved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id_productionoutput");

                    b.HasIndex("bmi_code");

                    b.HasIndex("id_pt");

                    b.ToTable("Production_output");
                });

            modelBuilder.Entity("BMI.Models.Rmmodel", b =>
                {
                    b.Property<int>("id_raw")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("cases")
                        .HasColumnType("int");

                    b.Property<string>("container")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("eta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("etd")
                        .HasColumnType("datetime2");

                    b.Property<float?>("ex_rate")
                        .HasColumnType("real");

                    b.Property<string>("landing_site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("qty_pl")
                        .HasColumnType("real");

                    b.Property<float?>("qty_received")
                        .HasColumnType("real");

                    b.Property<string>("raw_source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sap_code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("saved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<float?>("usd_price")
                        .HasColumnType("real");

                    b.HasKey("id_raw");

                    b.HasIndex("sap_code");

                    b.ToTable("Rm");
                });

            modelBuilder.Entity("BMI.Models.ShipmentDetailModel", b =>
                {
                    b.Property<int>("id_shipment_detail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("batch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bmi_code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_shipment")
                        .HasColumnType("int");

                    b.Property<float>("index")
                        .HasColumnType("real");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<string>("reff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id_shipment_detail");

                    b.HasIndex("bmi_code");

                    b.HasIndex("id_shipment");

                    b.ToTable("Shipment_detail");
                });

            modelBuilder.Entity("BMI.Models.Shipmentmodel", b =>
                {
                    b.Property<int>("id_shipment")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("eta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("etd")
                        .HasColumnType("datetime2");

                    b.Property<string>("po")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id_shipment");

                    b.ToTable("Shipment");
                });

            modelBuilder.Entity("BMI.Models.Usermodel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConfirmEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BMI.Models.DestroyModel", b =>
                {
                    b.HasOne("BMI.Models.MasterBMIModel", "MasterBMIModel")
                        .WithMany()
                        .HasForeignKey("bmi_code");

                    b.HasOne("BMI.Models.PTModel", "PTModel")
                        .WithMany()
                        .HasForeignKey("pt");
                });

            modelBuilder.Entity("BMI.Models.Fgmodel", b =>
                {
                    b.HasOne("BMI.Models.Masterdatamodel", "Masterdatamodel")
                        .WithMany("Fgmodels")
                        .HasForeignKey("sap_code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BMI.Models.ProductionInputModel", b =>
                {
                    b.HasOne("BMI.Models.MasterBMIModel", "MasterBMIModel")
                        .WithMany()
                        .HasForeignKey("bmi_code");

                    b.HasOne("BMI.Models.PTModel", "PTModel")
                        .WithMany()
                        .HasForeignKey("id_pt");
                });

            modelBuilder.Entity("BMI.Models.ProductionOutputModel", b =>
                {
                    b.HasOne("BMI.Models.MasterBMIModel", "MasterBMIModel")
                        .WithMany()
                        .HasForeignKey("bmi_code");

                    b.HasOne("BMI.Models.PTModel", "PTModel")
                        .WithMany()
                        .HasForeignKey("id_pt");
                });

            modelBuilder.Entity("BMI.Models.Rmmodel", b =>
                {
                    b.HasOne("BMI.Models.Masterdatamodel", "Masterdatamodel")
                        .WithMany("Rmmodels")
                        .HasForeignKey("sap_code");
                });

            modelBuilder.Entity("BMI.Models.ShipmentDetailModel", b =>
                {
                    b.HasOne("BMI.Models.MasterBMIModel", "MasterBMIModel")
                        .WithMany()
                        .HasForeignKey("bmi_code");

                    b.HasOne("BMI.Models.Shipmentmodel", "Shipmentmodel")
                        .WithMany()
                        .HasForeignKey("id_shipment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
